# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

source = ~/.config/hypr/keyboard.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/apps.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/window-rules.conf

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

