exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user enable --now hyprpolkitagent.service # Policy Kit Agent - So GTK apps can ask for elevation
exec-once = uwsm app -- hyprlock # Lockscreen
exec-once = uwsm app -- hyprpaper # Wallpaper
exec-once = uwsm app -- mako # Notifications
exec-once = uwsm app -- waybar # Status Bar
exec-once = uwsm app -- elephant # Menu Database
exec-once = uwsm app -- walker --gapplication-service # Popup Menu
exec-once = uwsm app -- hypridle
